basePath: /
definitions:
  main.HttpError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
info:
  contact: {}
  description: A simple example to show how swagger works.
  title: SwaggerExample
  version: "1.0"
paths:
  /posts/:
    get:
      consumes:
      - application/json
      description: gets all posts
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HttpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.HttpError'
      summary: All Posts
      tags:
      - posts
swagger: "2.0"
